vio_frame: false  #set false only if the system is needed to be tested with GPS odometry witout VIO enabled onboard UAV

#array of UAVs in the swarm. The first collumn is name ID of the drone (ID 26 is ID of UAV26 with IP 192.168.69.126), the second collumn is UVDAR ID
# UAVs: [26, 0, 
#        27, 1,
#        29, 2,
#        30, 3,
#        38, 4,
#        39, 5,
#        40, 6]

# UAVs: [29, 2,
#        30, 3,
#        38, 4,
#        39, 5]

UAVs: [29, 0,
       30, 1,
       38, 2,
       39, 3]